Delete release on fail via release id

diff --git a/.github/actions/delete-release-on-fail/action.yml b/.github/actions/delete-release-on-fail/action.yml
--- a/.github/actions/delete-release-on-fail/action.yml
+++ b/.github/actions/delete-release-on-fail/action.yml
@@ -14,5 +14,28 @@ runs:
   using: composite
   steps:
     - run: |
-      # ...
+        set -e
+
+        REPO="FLECS-Technologies/flecs-${{ inputs.name }}"
+        TAG="${{ inputs.tag }}"
+        TOKEN="${{ inputs.github_token }}"
+
+        echo "Searching Release-ID for tag: $TAG in repository: $REPO"
+
+        release_response=$(curl -s -H "Authorization: token $TOKEN" \
+          "https://api.github.com/repos/$REPO/releases/tags/$TAG")
+
+        release_id=$(echo "$release_response" | jq -r '.id')
+
+        if [[ "$release_id" == "null" || -z "$release_id" ]]; then
+          echo "No release found for $TAG"
+        else
+          echo "Delete release with ID $release_id"
+          curl -s -X DELETE -H "Authorization: token $TOKEN" \
+            "https://api.github.com/repos/$REPO/releases/$release_id"
+        fi
+
+        echo "Delete Git-Tag: $TAG"
+        curl -s -X DELETE -H "Authorization: token $TOKEN" \
+          "https://api.github.com/repos/$REPO/git/refs/tags/$TAG" || echo "Could not delete tag"
       shell: bash
